### PR TITLE
Try unmounting [..]/dev harder (issue #41)

### PR DESCRIPTION
**Pull request by hartwork**
Improved version of proposed fix to issue #41. Please consider for application :)

### CODE REVIEW

**Comment by hartwork** [comment]
Any news?

**Comment by mika** [comment]
Sorry, had no time to take a closer look at it yet :( Will do ASAP.

**Comment by hartwork** [comment]
It's been another month. The patch is rather trivial and tested. Please review. Thanks!

**Comment by mika** [comment]
Sorry for taking so long, merged with slightly adjusted commit message.Thanks!

**Comment by hartwork** [comment]
For the record, it's commit ccba9a85a1ad2e6aa405987195c1230e8a28c783.

**Pull request closed without merging**
