### PR TITLE
improve error handling

### PR DESCRIPTION
**Pull request by adrelanos**
WIP

Not yet tested. Will test soon.

My commit messages are more explanatory for the reviewer than useful in the git history of the master branch.

Due the difficulty and extensive scope of these changes, I won't be able to split this into different logical sets of changes.  It was so extensive, I had to randomly start somewhere and adjust it step by step for the new error handler.

I would suggest to squash all of these commits into a single commit since functionality wise hopefully nothing changed, just the error handling was improved and the code simplified.

Fixes https://github.com/grml/grml-debootstrap/issues/224

### CODE REVIEW

**Comment by adrelanos** [comment]
This is now tested with `--vmefi`. Images are bootable.

**Comment by adrelanos** [comment]
This was used to build Kicksecure and Whonix VM images. Seems stable. No issues.

**Comment by zeha** [comment]
This seems to break in some situations, example: https://github.com/zeha/grml-debootstrap/actions/runs/6906107865/job/18790415343

If you rebase this branch on top of current master, it should also get an actions pipeline.

**Comment by adrelanos** [comment]
I created a branch `error-handling2` because I wasn't sure if I should force push or if I messed up the rebase.

* https://github.com/grml/grml-debootstrap/pull/248

**Comment by adrelanos** [comment]
Seems a lot easier to rebase using github "Resolve conflicts" button than what I did locally:

1) git fetch grml
2) git checkout error-handling
3) git rebase grml-master
4) git mergetool

(Which is a 3 way diff using meld.)

A lot things I resolved manually I was wondering why git failed to merge this automatically.

Any hints for a better process?

**Pull request closed without merging**
