### PR TITLE
Support BOOT_APPEND usage outside of VMs

### PR DESCRIPTION
**Pull request by mika**
BOOT_APPEND works only for VMs when being invoked within `grub_install()` inside main grml-debootstrap, move its handling to chroot-script instead.

See https://github.com/grml/grml-debootstrap/issues/106

This is untested yet and needs verificiation e.g. via `grml-debootstrap --appendboot 'net.ifnames=0 biosdevname=0' ....` with:

1) testing with VM installation (`grml-debootstrap --vm ...`)
2) testing without VM installation (`grml-debootstrap --target /dev/sdX# ....`)

Testing welcome!

### CODE REVIEW

**Comment by suntong** [comment]
Is `grml-debootstrap` a single file or there are some dependencies? 
I can test it but need to understand how I can get it in my Live grml-small environment.

**Comment by mika** [comment]
@suntong no, `chroot-script` is also relevant (you can place 'chroot-scripts` as `/etc/debootstrap/chroot-script` though and then only `./grml-debootstrap` is relevant as well).

To make it simple for you I built a Debian package of my latest changes, so you can install it on your system and it should provide everything what's relevant:

  https://michael-prokop.at/tmp/grml-debootstrap_0.89~bootappend01_all.deb (md5sum: 1a8d0ec709fd6d11c8d1d3730b9cbc9a)

Just wget + `apt install ./grml-debootstrap_0.89~bootappend01_all.deb` it.

**Comment by suntong** [comment]
> To make it simple for you I built a Debian package... 

Thanks a lot mika, will do...

**Comment by suntong** [comment]
I tested `grml-debootstrap - version 0.89~bootappend01` and can confirm that the issue has been fixed for the case of without VM installation (`grml-debootstrap --target /dev/sdX`).

**Comment by mika** [comment]
This has been replaced with https://github.com/grml/grml-debootstrap/pull/142, closing hereby.
Thanks for your feedback, @suntong!

**Pull request closed without merging**
